export const InputNames={
    NAME: "name",
    PRICE:"price",
    RATING:"rating",
    IMG1:"img1",
    IMG_ARR:"imgArr",
    CREATED_AT:"createdAt",
    UPDATE_AT:"updatedAt",
    TYPE_ID:"typeId",
    BRAND_ID:"brandId",
    INFO:"info",
    SUB_CATEGORY_ID:"subCategoryId",
    SEARCH_QUERIES:"searchQueries",
    CURRENCY:"currency",
    UNIT:"unit",
    AVAILABILITY:" availability",
    LABEL:"label",
    WEIGHT:"weight",
    HEIGHT:"height",
    LENGTH:"length",
    LOCATION:"location",
    COLOR:"color",
    POWER:"power",
    CAPACITY: "capacity" ,
    COLOR_TEMP:"colorTemp",
    FAVORITE:"favotite" ,
    MODEL: "model",
    MADE_IN:"madeIn",
    OPT_PRICE:"optPrice",
    TYPE_NAME:"typeName",
    BRAND_NAME:"brandName"
 
  
}  